### ISSUE TITLE
Read PCAP from STDIN

### ISSUE THREAD

**Issue by MarcinNaw** [epl-viz/liblibwireshark#4]
How do you read a PCAP file from STDIN and start dissecting it?

`./simple_print -t manual file.pcap` works for a file, that is present in the file system.

Lets say I have an application, that returns a pcap file to the stdout. Most straightforward but useless example would be tcpdump:

`tcpdump -r file.pcap -w - | ./simple_print -t raw -` fails for me.

Do I get the syntax wrong or is this feature not implemented yet?

**Comment by a3f** [comment]
The `-t` option only accepts either `manual` or `text`, which determines how the output is presented: https://github.com/epl-viz/liblibwireshark/blob/889a36f445c01104723f46644e1311c38f340962/examples/00-simple-print.c#L34-L40

I haven't checked how Wireshark handles reading pcap streams from stdin. You could look at how `tshark` does it. Pull request to add explicit support for it here are welcome.

**Comment by MarcinNaw** [comment]
I think I just found the wireshark code responsible for reading the [stdin pipe "-"](https://github.com/epl-viz/wireshark/blob/20a174a1148c4726c48d726395fa105278a1e1ef/rawshark.c#L262-L263). So I hope to provide a pull request soon. 

Just to make sure to use your API as much as I can, could you maybe give a brief description on what ./example/02-seek-interactive-online, ./example/06-stdin-open and ./example/09-online-print do?

**Comment by a3f** [comment]
online-print, dissects and prints packets as they're captured.
seek-interactive-online, captures packets till Ctrl+C is received. After that it asks for a frame number, which you can seek to and selectively dissect.

The API was custom tailored for EPL-Viz' [DataCollect](https://github.com/epl-viz/EPL_DataCollect)'s needs. You can take a look there how its used, if the examples here don't suffice.

**Comment by a3f** [comment]
Resolved by #5.
